### ISSUE TITLE
Can't call overridden method

### ISSUE THREAD

**Issue by voropa** [Xotabu4/protractor-element-extend#20]
Hi!
I have tried to extend ElemetFinder and override it's "click" method, but when i call element.click() in my test scenario default ElementFinder click() event is fired. Here is the example of my code below.

`export default class ElementDecorator extends BaseFragment {
  protected logger = CustomLogger.get('ElementDecorator');

  constructor(elementFinder: ElementFinder) {
    super(elementFinder);
  }

  public async click(): Promise<void> {
    this.logger.info('my click');
    await this.scrollIntoView();
    await WaitUtils.waitForClickable(this);
    await super.click();
  }
}

export default class MyPageObjectClass {
private myButton: ElementDecorator;

constructor() {
this.myButton= new ElementDecorator($(#button));
}

public async clickMyButton() {
    this.logger.info('Clicking my button');
    await this.myButton.click();
}
}`

    "protractor": "5.4.2",
    "typescript": "3.4.1"

**Comment by Xotabu4** [comment]
@voropa I can't reproduce,
```
    class ElementDecorator extends BaseFragment {
        async click() {
            console.log("overriden click");
            await super.click();
        }
    }

    class MyPageObjectClass {
        constructor() {
            this.myButton = new ElementDecorator($("#checkbox-example button"));
        }

        async clickMyButton() {
            console.log('clicking button')
            await this.myButton.click();
        }
    }
```

Getting correct output:

```
> protractor

[12:42:53] I/launcher - Running 1 instances of WebDriver
[12:42:53] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
Started
clicking button
Got text: It's gone!
.
```

**Comment by voropa** [comment]
Seems that i've found the root of the problem.
Actually we could  override ElementFinder class methods as we extends it. For example isPresent() method could be overriden  and  works good. But as for other native selenium methods like click, sendKeys, isDisplayed: they are declared inside WebdriverWebElement interface and override doesn't work for them.

export default class ElementDecorator extends ElementFinder {
  /**
   * Extend this class, to describe single custom fragment on your page
   *
   * @param {ElementFinder} elementFinder ElementFinder that you want to extend
   */
  constructor(elementFinder: ElementFinder) {
    // Basically we are recreating ElementFinder again with same parameters
    super(elementFinder.browser_, elementFinder.elementArrayFinder_);
  }
// Works fine
  public async isPresent(): Promise<boolean> {
    console.log('my isPresent');
    return super.isPresent();
  }
// Doesn't work
  public async isDisplayed(): Promise<boolean> {
    console.log('my isDisplayed');
    return super.isDisplayed();
  }
}

**Comment by Xotabu4** [comment]
@voropa 
Yes, i also did investigation. Protractor has monkey-patching for some of the methods - https://github.com/angular/protractor/blob/master/lib/element.ts#L831

This patching seems to be applied AFTER instance is created, so it override your declared methods in 
ElementDecorator. And also this added methods seems to be NOT available on 'super' because of this patching.

I will take a look how this can be fixed on protractor-element-extend level.

Thanks for bug report!

For now, as a workaround i can suggest to not override methods:
```
    class ElementDecorator extends BaseFragment {
        constructor(el) {
            super(el)
        }

        async myClick() {
            console.log('OWN click')
            await this.click()
        }
    }
```

**Comment by voropa** [comment]
> @voropa
> Yes, i also did investigation. Protractor has monkey-patching for some of the methods - https://github.com/angular/protractor/blob/master/lib/element.ts#L831
> 
> This patching seems to be applied AFTER instance is created, so it override your declared methods in
> ElementDecorator. And also this added methods seems to be NOT available on 'super' because of this patching.
> 
> I will take a look how this can be fixed on protractor-element-extend level.
> 
> Thanks for bug report!
> 
> For now, as a workaround i can suggest to not override methods:
> 
> ```
>     class ElementDecorator extends BaseFragment {
>         constructor(el) {
>             super(el)
>         }
> 
>         async myClick() {
>             console.log('OWN click')
>             await this.click()
>         }
>     }
> ```

Sure. And I've found  another workaround but it is  not  stable and depends on elementArrayFinder realization.
![image](https://user-images.githubusercontent.com/14195681/60095381-13b3a500-9757-11e9-8f96-34453b5927cd.png)

**Comment by voropa** [comment]
Anyway protractor and native selenium action methods are protected from overriding by default.

**Comment by Xotabu4** [comment]
@voropa 
Hi, i think i have solution.

Can you please test with `2.3.0-alpha-2` version that is published to NPM ?
I tested manually and it looks good from my side. 

And also i fixed same issue for BaseArrayFragment also

**Comment by voropa** [comment]
@Xotabu4 
Thank you  for update but unfortunately it still doesn't work for me((
![image](https://user-images.githubusercontent.com/14195681/60708655-3bed9180-9f17-11e9-9b26-debd0055f8fd.png)
![image](https://user-images.githubusercontent.com/14195681/60708821-9ab30b00-9f17-11e9-9e08-1ed3d6d8ece8.png)


And then  i'm getting TypeError when  trying to  run the test  using  this element wrapper:
 Message:
    Failed: Cannot read property 'apply' of undefined
  Stack:
    TypeError: Cannot read property 'apply' of undefined
        at MyElement.(anonymous function).args [as click] (C:\workspace\SSL\selenium\test-protractor-project-ts\node_modules\protractor\built\element.js:831:22)
        at Object.<anonymous> (C:\workspace\SSL\selenium\test-protractor-project-ts\e2e\onliner.spec.ts:12:35)
        at Generator.next (<anonymous>)
        at C:\workspace\SSL\selenium\test-protractor-project-ts\tmp\e2e\onliner.spec.js:7:71
        at new Promise (<anonymous>)
        at __awaiter (C:\workspace\SSL\selenium\test-protractor-project-ts\tmp\e2e\onliner.spec.js:3:12)
        at UserContext.it (C:\workspace\SSL\selenium\test-protractor-project-ts\e2e\onliner.spec.ts:11:31)
        at C:\workspace\SSL\selenium\test-protractor-project-ts\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (C:\workspace\SSL\selenium\test-protractor-project-ts\node_modules\selenium-webdriver\lib\promise.js:1077:7)
        at ControlFlow.promise (C:\workspace\SSL\selenium\test-protractor-project-ts\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    From: Task: Run it("first test") in control flow
        at UserContext.<anonymous> (C:\workspace\SSL\selenium\test-protractor-project-ts\node_modules\jasminewd2\index.js:94:19)
    From asynchronous test:
    Error
        at Object.<anonymous> (C:\workspace\SSL\selenium\test-protractor-project-ts\e2e\onliner.spec.ts:11:3)
        at Generator.next (<anonymous>)
        at C:\workspace\SSL\selenium\test-protractor-project-ts\tmp\e2e\onliner.spec.js:7:71
        at new Promise (<anonymous>)
        at __awaiter (C:\workspace\SSL\selenium\test-protractor-project-ts\tmp\e2e\onliner.spec.js:3:12)
        at Suite.fdescribe (C:\workspace\SSL\selenium\test-protractor-project-ts\e2e\onliner.spec.ts:4:41)

**Comment by Xotabu4** [comment]
@voropa https://github.com/angular/protractor/pull/5328
This fix to protractor should fix this issue as well

**Comment by Skidush** [comment]
Hello. Any updates on this issue? I wrap my own classes so its not really nice to see methods `myClick()` and `click()` existing on the same object.

**Comment by Xotabu4** [comment]
@Skidush Hello, unfortunately i can't fix this on library side. Protractor uses monkey patching after constructor was called, so all methods from this list

```
let WEB_ELEMENT_FUNCTIONS = [
'click', 'sendKeys', 'getTagName', 'getCssValue', 'getAttribute', 'getText', 'getRect',
'isEnabled', 'isSelected', 'submit', 'clear', 'isDisplayed', 'getId', 'takeScreenshot'
];
```

are patched after extended component is created so this overrides methods back to default.

I will ask protractor team again to merge PR and release a new version.

**Comment by Skidush** [comment]
> @Skidush Hello, unfortunately i can't fix this on library side. Protractor uses monkey patching after constructor was called, so all methods from this list
> 
> ```
> let WEB_ELEMENT_FUNCTIONS = [
> 'click', 'sendKeys', 'getTagName', 'getCssValue', 'getAttribute', 'getText', 'getRect',
> 'isEnabled', 'isSelected', 'submit', 'clear', 'isDisplayed', 'getId', 'takeScreenshot'
> ];
> ```
> 
> are patched after extended component is created so this overrides methods back to default.
> 
> I will ask protractor team again to merge PR and release a new version.

Wow that was quick. Thanks for the response!

Great library btw!
